[package]
name = "itzel-desktop"
version = "0.1.0"
description = "Itzel — IA personal local, open source y comunitaria"
authors = ["Edwin Yair Hernández Limón <edwinyhl.dev@gmail.com>"]
license = "MIT"
repository = "https://github.com/BugCreator404/itzel"
edition = "2021"

[lib]
name = "itzel_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-shell = "2"
tauri-plugin-notification = "2"
tauri-plugin-global-shortcut = "2"
tauri-plugin-clipboard-manager = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
